image: quantumtinkerer/research

## Documentation for the format of this file can be found here:
## https://docs.gitlab.com/ce/ci/yaml/README.html#configuration-of-your-builds-with-gitlab-ci-yml

test build:
  stage: build
  script: python setup.py develop
  artifacts:
    paths:
      - semicon/model_cache.json
    expire_in: 2 hour

test linting:
  script:
    - conda env create -f docker/semicon-stable.yml
    - source activate semicon-stable
    - pre-commit install
    - pre-commit run --all
  stage: test

test stable requirements:
  script:
    - conda env create -f docker/semicon-stable.yml
    - source activate semicon-stable
    - py.test semicon/ --cov=semicon --verbose --cov-report term
  stage: test

test latest requirements:
  script:
    - conda env create -f docker/semicon-latest.yml
    - source activate semicon-latest
    - py.test semicon/ --cov=semicon --verbose --cov-report term
  stage: test

test packaging:
  script:
    - conda env create -f docker/semicon-stable.yml
    - source activate semicon-stable
    - python setup.py install
    - cd /  # make sure we don't import the cloned version
    - python -c 'import semicon; semicon.test()'
  stage: test
