image: kwant/testing

stages:
  - build
  - test

build package:
  stage: build
  script:
    - python3 setup.py build


test package:
  stage: test
  script:
    - pip3 install sympy==1.1.1
    - pip3 install .
    - py.test -r w --cov semicon --cov-report term --flakes semicon


test package with latest scipy:
  stage: test
  script:
    - pip3 install sympy==1.1.1 scipy==1.2.0rc2
    - pip3 install .
    - py.test -r w --cov semicon --cov-report term --flakes semicon


test package with latest SymPy and Kwant stable:
  stage: test
  script:
    - pip3 install sympy
    - pip3 install git+https://gitlab.kwant-project.org/kwant/kwant.git@stable
    - pip3 install .
    - py.test -r w --cov semicon --cov-report term --flakes semicon
